config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'clicks#show'
  resources :clicks, only: [:show, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/click.rb
class Click < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clicks_controller.rb
class ClicksController < ApplicationController
  def show
    # get city
    city = request.location.city || 'Mars'
    # find or create
    @click = Click.find_or_create_by(city: city)
  end

  def update
    @click = Click.find(params[:id])
    @click.update!(click: @click.click + 1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clicks/show.html.erb
<div id="app" class="container-sm">
  
  <div class="jumie c">
    <h1><%= @click.city %></h1>
    <div id="counter" class="rot-c"><%= @click.click %></div>
  </div>
  <%= link_to "", click_path(@click), method: :put, id: 'click-link' %> 
</div>

<style type="text/css">
#app,body,html {
    height: 100%;
    overflow: hidden
}
body {
    margin: 0;
    background-color: #bdaa90;
    -ms-user-select: none;
    user-select: none;
    -moz-user-select: none;
    -webkit-user-select: none;
    position: relative;
    font-family: Nunito,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji
}
#app {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  position: relative
}
.jumie {
  height: 0;
  flex-grow: 1;
  width: 100%;
  max-width: 800px;
  background-position: bottom;
  background-size: contain;
  background-repeat: no-repeat;
  touch-action: manipulation;
  text-align: center;
  color: #fff;
  -webkit-text-stroke-width: 3px;
  -webkit-text-stroke-color: #000;
  font-weight: 900;
  font-size: 80px;
  word-wrap: break-word
}
.c {
  background-image: url('/assets/pop-jumie-c.png');
}
.op {
  background-image: url('/assets/pop-jumie-op.png');
}
@media(min-width: 1000px) {
  .jumie {
      font-size:40px;
      -webkit-text-stroke-width: 1.5px
  }
}
h1 {
  font-size: 60px;
  margin: 14px;
}
</style>

<script type="text/javascript">
  $(document).mouseup(function() {
    $('.jumie').removeClass("op").addClass("c");
  });
  $(document).mousedown(function() {
    $('.jumie').removeClass("c").addClass("op");
    $('#click-link')[0].click();
    $('#counter').html(function(i, val) { return +val+1 });
  });
  $(document).keyup(function() {
    $('.jumie').removeClass("op").addClass("c");
  });
  $(document).keydown(function() {
    $('.jumie').removeClass("c").addClass("op");
    $('#click-link')[0].click();
    $('#counter').html(function(i, val) { return +val+1 });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag '/assets/pop-jumie-icon.png' %>
    <title>PopJumie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>